export const GENRES = [
  // Block 1: The Foundation (Classical & Tradition)
  "classic",
  "crossover",
  "score",
  "soundtrack",
  "spiritual",
  "gospel",
  "world",
  "ethno",
  "choir",

  // Block 2: Groove & Heartbeat (Black Music & Roots)
  "jazz",
  "blues",
  "swing",
  "rnb",
  "funk",
  "disco",
  "soul",
  "reggae",
  "ska",
  "dancehall",
  "latin",
  "salsa",
  "reggaeton",
  "afrobeat",
  "highlife",
  "soukous",
  "rap",

  // Block 3: Energy & Rebellion (Guitars & Amps)
  "rock",
  "metal",
  "punk",
  "indie",
  "alternative",
  "shoegaze",
  "krautrock",
  "rockabilly",
  "psychobilly",
  "gothic",
  "industrial",
  "hardcore",

  // Block 4: Modernity & Technology (Pop & Synthetics)
  "pop",
  "urban",
  "electronic",
  "edm",
  "songwriter",
  "country",
  "folk",
  "bluegrass",

  // Block 5: Experiments & Function (Niches & Special Formats)
  "avantgarde",
  "experimental",
  "microgenres",
  "sound art",
  "field recordings",
  "spoken word",
  "comedy",
  "kids",
  "marching band",
];